### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by rhaleblian**

### CODE REVIEW

**Comment by jay-reynolds** [comment]
This reminds me of the time I got confused about what the top half of a fraction is called.

LGTM.   Ship it!

**Comment by jay-reynolds** [comment]
I've been doing a lot of stuff with Langchain lately.  You should check it out.  I mean, if you're into that sort of thing.

https://github.com/hwchase17/langchain

**Comment by rhaleblian** [comment]
What do you mean?  I dance Langchain-style.

**Comment by rhaleblian** [comment]
The top half of a fraction is called "the top".

**Comment by jay-reynolds** [comment]
That's true, actually.

**Comment by rhaleblian** [comment]
I'm not on Discord much but I think when my machine setups settle down I'll be on there more regularly.

**Comment by jay-reynolds** [comment]
This is extreme chat.

**Comment by rhaleblian** [comment]
We have to review, approve or reject our own _chatting_ .   That's hardcore.

**Comment by jay-reynolds** [comment]
lgtm.

**Comment by jay-reynolds** [comment]
lgtm.

**Comment by rhaleblian** [comment]
Watch out or i'll reopen this.

**Comment by jay-reynolds** [comment]
Oh, hey.  I ended up landing that gig.  Forgot if I had mentioned that.  Passed the background check.  Officially not a war criminal.

**Comment by rhaleblian** [comment]
Congratulations!

**Comment by rhaleblian** [comment]
Get me some free Meta stuff.  I might have a couple of app ideas.

**Comment by jay-reynolds** [comment]
ON IT.

**Pull request merged**
